# Generated by Django 6.0.3 on 2026-04-07 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='country',
            field=models.CharField(default=6108001958, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='hrc245@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.TextField(default='This is a defaut message.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='Haynes Cromartie', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
